spring:

#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/notedb
#    username: root
#
#  jpa:
#    openInView: false
#    show_sql: true
#    generate-ddl: false
#    hibernate:
#      ddl-auto: create

  data:
    mongodb:
      database: mydb